import { resolve } from 'path';
import envVars from 'preact-cli-plugin-env-vars';

export default {
    /**
     * Function that mutates the original webpack config.
     * Supports asynchronous changes when a promise is returned (or it's an async function).
     *
     * @param {object} config - original webpack config.
     * @param {object} env - options passed to the CLI.
     * @param {WebpackConfigHelpers} helpers - object with useful helpers for working with the webpack config.
     * @param {object} options - this is mainly relevant for plugins (will always be empty in the config), default to an empty object
     **/
    webpack(config, env, helpers, options) {
        envVars(config, env, helpers); // gives access to process.env.PREACT_APP_XYZ env vars.

        console.log('----- config -----')
        console.log(config)
        console.log('----- end config -----')

        console.log('----- config.module.rules -----')
        console.log(config.module.rules)
        console.log('----- end config -----')


        console.log('----- env -----')
        console.log(env)
        console.log('----- end env -----')
        
        if (!env.production) {
            config.devServer.overlay = true;
            config.devServer.hot = false;

            console.log('add @babel/plugin-transform-react-jsx-source')
            const { rule } = helpers.getLoadersByName(config, 'babel-loader')[0];
            rule.options.plugins.push(require.resolve('@babel/plugin-transform-react-jsx-source'));
        }
        
        config.module.rules[4].use.splice(1, 0, {
            loader: '@teamsupercell/typings-for-css-modules-loader',
            options: {
                banner:
                    '// This file is automatically generated from your CSS. Any edits will be overwritten.',
                disableLocalsExport: true
            }
        });

        // Use any `index` file, not just index.js
        config.resolve.alias['preact-cli-entrypoint'] = resolve(
            process.cwd(),
            'src',
            'index'
        );

        // https://github.com/preactjs-templates/widget/blob/4f6944a3337205775ab3c06571489290a61057f6/template/preact.config.js#L5

        // if (env.production) {
        //     config.output.libraryTarget = "umd";
        // }

        {
            const { rule } = helpers.getLoadersByName(config, 'babel-loader')[0];
            const babelConfig = rule.options;

            console.log('----- babelConfig -----')
            console.log(babelConfig)
            console.log('----- end babelConfig -----')

        }
    }
};
